largest = int(input())
medium = int(input())
smallest = int(input())
largest, medium = max(largest, medium), min(largest, medium)
medium, smallest = max(medium, smallest), min(smallest, medium)
largest, medium = max(largest, medium), min(largest, medium)
print(largest)
print(medium)
print(smallest)